version: '3.8'

services:
  # FastAPI Uygulaması
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./imagess:/app/imagess
    restart: unless-stopped
    network_mode: "host"